language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - "7.0"
    - hhvm
    - nightly



matrix:
    allow_failures:
        - php: hhvm
        - php: nightly



before_script:
    # Store all files in your own bin
    - mkdir bin
    - export PATH=$PATH:$PWD/bin/

    # Install phpcs
    - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
    - install --mode 0755 phpcs.phar $PWD/bin/phpcs

    #- wget http://getcomposer.org/composer.phar
    #- php composer.phar install --no-interaction
    - wget https://scrutinizer-ci.com/ocular.phar

    # Composer
    - composer validate
    - composer update


script: 
    - php --version
    - phpcs --version
    - composer --version
    - phpunit --version

    - mkdir -p build/logs
    - phpunit --bootstrap test/config.php --coverage-clover build/logs/clover.xml test
    - make test



after_script:
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml



notifications:
    irc: "irc.freenode.org#dbwebb"
    webhooks:
        urls:
          - https://webhooks.gitter.im/e/86877cd2fec2eb37da31
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: never     # options: [always|never|change] default: always
